# docker-compose.yml - 完全コンテナ化対応版

services:
  # Goアプリケーションサービス（新規追加）
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-todo-app
    ports:
      - "${PORT:-8080}:8080"
    environment:
      # 重要：DB_HOSTをpostgresに変更
      - PORT=8080
      - DB_HOST=postgres  # ← localhost から postgres に変更！
      - DB_PORT=5432
      - DB_USER=${DB_USER:-todouser}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-todoapp}
      - DB_SSL_MODE=${DB_SSL_MODE:-disable}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped

  # PostgreSQLデータベースサービス（既存）
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-todouser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-todoapp}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-todouser} -d ${DB_NAME:-todoapp}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  todo-network:
    driver: bridge