# .github/workflows/ci.yml
# サブディレクトリ対応版 CI Pipeline（修正版）

name: Go Todo CI Pipeline

# go-todoディレクトリに変更があった時のみ実行
on:
  push:
    branches: [ main, develop ]
    paths:
      - 'go-todo/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'go-todo/**'

jobs:
  # ジョブ1: Go アプリケーションのテスト・ビルド
  test-and-build:
    name: Test and Build Go App
    runs-on: ubuntu-latest

    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Go環境のセットアップ
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # 3. 依存関係のキャッシュ
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go-todo/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # 4. 依存関係のダウンロード
    - name: Download dependencies
      working-directory: ./go-todo
      run: go mod download

    # 5. 依存関係の検証
    - name: Verify dependencies
      working-directory: ./go-todo
      run: go mod verify

    # 6. コードフォーマットチェック
    - name: Check code format
      working-directory: ./go-todo
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly:"
          gofmt -s -l .
          exit 1
        fi

    # 7. 静的解析（vet）
    - name: Run go vet
      working-directory: ./go-todo
      run: go vet ./...

    # 8. テスト実行（今後追加予定）
    - name: Run tests
      working-directory: ./go-todo
      run: |
        echo "Tests will be added in future iterations"
        # go test -v ./...

    # 9. ビルド実行
    - name: Build application
      working-directory: ./go-todo
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
          -ldflags='-w -s -extldflags "-static"' \
          -a -installsuffix cgo \
          -trimpath \
          -tags 'netgo osusergo' \
          -o main .

    # 10. ビルド成果物の確認
    - name: Check build artifact
      working-directory: ./go-todo
      run: |
        ls -lh main

  # ジョブ2: Docker イメージのビルド・検証
  docker-build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Docker Buildx のセットアップ
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Dockerイメージのビルド（go-todoディレクトリから）
    - name: Build Docker image
      working-directory: ./go-todo
      run: |
        docker build -t go-todo:ci-test .

    # 4. イメージサイズの確認
    - name: Check Docker image size
      run: |
        echo "=== Docker Image Size ==="
        docker images go-todo:ci-test

    # 5. イメージの脆弱性チェック（基本版）
    - name: Run basic security scan
      run: |
        echo "=== Basic Security Check ==="
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasecurity/trivy:latest image go-todo:ci-test

    # 6. コンテナの起動テスト（データベース接続なしで簡易テスト）
    - name: Test container startup
      run: |
        echo "=== Container Startup Test ==="
        # コンテナ起動（データベース接続は失敗するが、起動自体はテスト）
        timeout 10s docker run --name test-container go-todo:ci-test || echo "Container started (DB connection expected to fail in CI)"
        
        # ログ確認
        echo "Container logs:"
        docker logs test-container || echo "No logs available"
        
        # クリーンアップ
        docker rm test-container || echo "Container already removed"

  # ジョブ3: コード品質チェック
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Go環境のセットアップ
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # 3. golangci-lint のインストール・実行（修正版）
    - name: Run golangci-lint
      working-directory: ./go-todo
      run: |
        # golangci-lintをインストール
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        # lintを実行
        golangci-lint run --timeout=5m

    # 4. ファイルサイズチェック
    - name: Check file sizes
      working-directory: ./go-todo
      run: |
        echo "=== Large Files Check ==="
        find . -type f -size +1M -not -path "./.git/*" -not -path "./vendor/*" || true

    # 5. セキュリティ面のチェック
    - name: Security check with gosec
      working-directory: ./go-todo
      run: |
        go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
        gosec ./... || echo "Security issues found - review required"